---
on: push
name: Build and publish
branches: master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # - name: Branch filter
      #   uses: actions/bin/filter@master
      #   with:
      #     args: branch master

      - name: Build
        # uses: framer/bridge@master
        uses: echo build

        # with:
        # args: build design-system.framerfx
        # args: echo building project
      - name: Publish
        uses: echo publish
        # uses: framer/bridge@master
        # env:
        #   FRAMER_TOKEN: ${{ secrets.FRAMER_TOKEN }}
        # with:
        # args: publish design-system.framerfx --yes
        # args: echo publishing to the store!
